name: Deploy Demo to GitHub Pages

on:
  push:
    branches: ["main"]

# Give the Action permission to read code and write to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      - name: Install dependencies
        run: npm install
        
      - name: Build SDK
        run: npm run build:all
        
      - name: Prepare Demo Folder
        run: |
          mkdir public
          cp -r demo/* public/
          mkdir -p public/sdk/dist
          cp -r dist/* public/sdk/dist/
          # Fix path referencing so GitHub Pages can load the script properly
          sed -i 's|/sdk/dist/|./sdk/dist/|g' public/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
